variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    - integrationTest

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test --filter TestCategory!=\"Integration\""
  
integrationTest:
    stage: integrationTest
    only: 
        - schedules
    tags:
    - nuix
    script:
        - "dotnet test --filter TestCategory=\"Integration\""