stages:
    - build
    - test
    - integrationTest

build:
    stage: build
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    script:
        - dotnet nuget add source -n reductech -u $GITLAB_NUGET_USERNAME -p $GITLAB_NUGET_PAT --store-password-in-clear-text "https://gitlab.com/api/v4/projects/18697166/packages/nuget/index.json"
        - "dotnet build"

test:
    stage: test
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    script: 
        - dotnet nuget add source -n reductech -u $GITLAB_NUGET_USERNAME -p $GITLAB_NUGET_PAT --store-password-in-clear-text "https://gitlab.com/api/v4/projects/18697166/packages/nuget/index.json"
        - "dotnet test --filter TestCategory!=\"Integration\""
  
integrationTest:
    stage: integrationTest
    only: 
        - schedules
    tags:
        - nuix
    script:
        - dotnet nuget add source -n reductech -u $GITLAB_NUGET_USERNAME -p $GITLAB_NUGET_PAT --store-password-in-clear-text "https://gitlab.com/api/v4/projects/18697166/packages/nuget/index.json"
        - "dotnet test --filter TestCategory=\"Integration\""