include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.windows.yml

stages:
  - build
  - test
  - integration
  - quality
  - package
  - sign
  - push

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH !~ /^\d+-/
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'schedule'

variables:
  PACKAGE_NAME_NUGET: Reductech.EDR.Connectors.Nuix
  PACKAGE_NAME_DLL: Reductech.EDR.Connectors.Nuix

.get_coverage:
  - &get_coverage |
    $report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
    $fixPaths = $report -replace "filename=`".+?${env:CI_PROJECT_NAME}(/|\\)", "filename=`"" ;
    [System.IO.File]::WriteAllText("./coverage.cobertura.xml", $fixPaths) ;
    $xml = [xml]$report ;
    $branchCoverage = [double]($xml.coverage."branch-rate") * 100 ;
    $lineCoverage = [double]($xml.coverage."line-rate") * 100 ;
    Write-Host "Coverage (Branch) : ${branchCoverage}%" ;
    Write-Host "Coverage (Line)   : ${lineCoverage}%"

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --filter "Category!=Integration"
      --collect:"XPlat Code Coverage" --results-directory ./
    - *get_coverage

integration test:
  stage: integration
  extends:
    - .default_before_script
  needs: []
  tags:
    - nuix
  variables:
    CONFIG: $CONFIG_DEV
    NUGET_PROJECT_ID: $NUGET_PROJECT_ID_DEV
    NUGET_USERNAME: $NUGET_USER_DEV
    NUGET_TOKEN: $NUGET_TOKEN_DEV
  after_script:
    - dotnet nuget remove source reductech
  script:
    - dotnet restore --packages ./packages
    - dotnet test --no-restore --configuration $CONFIG
      --collect:"XPlat Code Coverage" --results-directory ./
      -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=false
    - *get_coverage
  coverage: /Coverage \(Branch\)[\s:]+(\d+.?\d*)%/
  artifacts:
    reports:
      cobertura: coverage.cobertura.xml
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: &not_release $CI_COMMIT_TAG !~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?$/i
      when: manual
      allow_failure: true

integration test release:
  extends:
    - integration test
    - .rules_release
  variables:
    CONFIG: $CONFIG_RELEASE
    NUGET_PROJECT_ID: $NUGET_PROJECT_ID_RELEASE
    NUGET_USERNAME: $NUGET_USER_PROD
    NUGET_TOKEN: $NUGET_TOKEN_PROD

# Skipping mutation testing as Stryker currently doesn't support filters
mutation testing:
  rules:
    - when: never
