variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - test
    - integrationTest

build:
    stage: build
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    script:
        - "dotnet nuget add source https://gitlab.com/api/v4/projects/17256122/packages/nuget/index.json -n InstantConsole -u MarkWainwright -p eTL5EYHQPELP1vSeBs-k"
        - "dotnet build"

test:
    stage: test
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    script: 
        - "dotnet test --filter TestCategory!=\"Integration\""
  
integrationTest:
    stage: integrationTest
    only: 
        - schedules
    tags:
        - nuix
    script:
        - "dotnet test --filter TestCategory=\"Integration\""