variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test --filter TestCategory!=\"Integration\""